# This workflow will build and push a docker image to dockerhub
name: Main Docker

on:
  pull_request:
    branches: ["dev"]
  workflow_run:
    workflows: ["Main and Dev CICD datafog-api app"]
    branches:
      - main
    types:
      - completed

jobs:
  build-and-push-docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Cache Docker layers
        uses: actions/cache@v4
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: datafog/datafog-api:latest,datafog/datafog-api:1-latest
          platforms: linux/amd64,linux/arm64/v8
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
      - name: Update Docker Hub README
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_ACCESS_TOKEN: ${{ secrets.DOCKERHUB_PASSWORD }}
        run: |
          # Get the current README.md content
          README_CONTENT=$(cat README.md)
  
          # Define the Docker Hub API URL
          API_URL="https://hub.docker.com/v2/repositories/datafog/datafog-api/"
  
          # Create JSON payload
          JSON_PAYLOAD=$(jq -n --arg msg "$README_CONTENT" '{"full_description": $msg}')
  
          # Send a PATCH request to update the description
          curl -s -X PATCH -H "Content-Type: application/json" -H "Authorization: JWT $(curl -s -H "Content-Type: application/json" -X POST -d "{\"username\": \"$DOCKER_USERNAME\", \"password\": \"$DOCKER_ACCESS_TOKEN\"}" https://hub.docker.com/v2/users/login/ | jq -r .token)" -d "$JSON_PAYLOAD" $API_URL
